/*!
 * Copyright (c) 2019-2021 TUXEDO Computers GmbH <tux@tuxedocomputers.com>
 *
 * This file is part of TUXEDO Control Center.
 *
 * TUXEDO Control Center is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * TUXEDO Control Center is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with TUXEDO Control Center.  If not, see <https://www.gnu.org/licenses/>.
 */

export interface ITccFanProfile {
    name?: string;
    tableCPU?: ITccFanTableEntry[];
    tableGPU?: ITccFanTableEntry[];
}

export interface ITccFanTableEntry {
    temp: number;
    speed: number;
}

export const defaultFanProfiles: ITccFanProfile[] = [
    {
        name: "Silent",
        tableCPU: [
            { temp: 0, speed: 0 },
            { temp: 1, speed: 0 },
            { temp: 2, speed: 0 },
            { temp: 3, speed: 0 },
            { temp: 4, speed: 0 },
            { temp: 5, speed: 0 },
            { temp: 6, speed: 0 },
            { temp: 7, speed: 0 },
            { temp: 8, speed: 0 },
            { temp: 9, speed: 0 },
            { temp: 10, speed: 0 },
            { temp: 11, speed: 0 },
            { temp: 12, speed: 0 },
            { temp: 13, speed: 0 },
            { temp: 14, speed: 0 },
            { temp: 15, speed: 0 },
            { temp: 16, speed: 0 },
            { temp: 17, speed: 0 },
            { temp: 18, speed: 0 },
            { temp: 19, speed: 0 },
            { temp: 20, speed: 0 },
            { temp: 21, speed: 0 },
            { temp: 22, speed: 0 },
            { temp: 23, speed: 0 },
            { temp: 24, speed: 0 },
            { temp: 25, speed: 0 },
            { temp: 26, speed: 0 },
            { temp: 27, speed: 0 },
            { temp: 28, speed: 0 },
            { temp: 29, speed: 0 },
            { temp: 30, speed: 11 },
            { temp: 31, speed: 11 },
            { temp: 32, speed: 11 },
            { temp: 33, speed: 11 },
            { temp: 34, speed: 11 },
            { temp: 35, speed: 11 },
            { temp: 36, speed: 11 },
            { temp: 37, speed: 11 },
            { temp: 38, speed: 11 },
            { temp: 39, speed: 11 },
            { temp: 40, speed: 11 },
            { temp: 41, speed: 11 },
            { temp: 42, speed: 11 },
            { temp: 43, speed: 11 },
            { temp: 44, speed: 11 },
            { temp: 45, speed: 11 },
            { temp: 46, speed: 11 },
            { temp: 47, speed: 11 },
            { temp: 48, speed: 11 },
            { temp: 49, speed: 11 },
            { temp: 50, speed: 11 },
            { temp: 51, speed: 11 },
            { temp: 52, speed: 11 },
            { temp: 53, speed: 11 },
            { temp: 54, speed: 11 },
            { temp: 55, speed: 34 },
            { temp: 56, speed: 34 },
            { temp: 57, speed: 34 },
            { temp: 58, speed: 34 },
            { temp: 59, speed: 34 },
            { temp: 60, speed: 34 },
            { temp: 61, speed: 34 },
            { temp: 62, speed: 34 },
            { temp: 63, speed: 34 },
            { temp: 64, speed: 34 },
            { temp: 65, speed: 34 },
            { temp: 66, speed: 34 },
            { temp: 67, speed: 34 },
            { temp: 68, speed: 34 },
            { temp: 69, speed: 34 },
            { temp: 70, speed: 34 },
            { temp: 71, speed: 34 },
            { temp: 72, speed: 34 },
            { temp: 73, speed: 34 },
            { temp: 74, speed: 34 },
            { temp: 75, speed: 34 },
            { temp: 76, speed: 34 },
            { temp: 77, speed: 34 },
            { temp: 78, speed: 34 },
            { temp: 79, speed: 34 },
            { temp: 80, speed: 34 },
            { temp: 81, speed: 34 },
            { temp: 82, speed: 34 },
            { temp: 83, speed: 34 },
            { temp: 84, speed: 34 },
            { temp: 85, speed: 34 },
            { temp: 86, speed: 34 },
            { temp: 87, speed: 34 },
            { temp: 88, speed: 34 },
            { temp: 89, speed: 34 },
            { temp: 90, speed: 34 },
            { temp: 91, speed: 34 },
            { temp: 92, speed: 36 },
            { temp: 93, speed: 36 },
            { temp: 94, speed: 36 },
            { temp: 95, speed: 36 },
            { temp: 96, speed: 36 },
            { temp: 97, speed: 36 },
            { temp: 98, speed: 36 },
            { temp: 99, speed: 36 },
            { temp: 100, speed: 36 }
        ],
        tableGPU: [
            { temp: 0, speed: 0 },
            { temp: 1, speed: 0 },
            { temp: 2, speed: 0 },
            { temp: 3, speed: 0 },
            { temp: 4, speed: 0 },
            { temp: 5, speed: 0 },
            { temp: 6, speed: 0 },
            { temp: 7, speed: 0 },
            { temp: 8, speed: 0 },
            { temp: 9, speed: 0 },
            { temp: 10, speed: 0 },
            { temp: 11, speed: 0 },
            { temp: 12, speed: 0 },
            { temp: 13, speed: 0 },
            { temp: 14, speed: 0 },
            { temp: 15, speed: 0 },
            { temp: 16, speed: 0 },
            { temp: 17, speed: 0 },
            { temp: 18, speed: 0 },
            { temp: 19, speed: 0 },
            { temp: 20, speed: 0 },
            { temp: 21, speed: 0 },
            { temp: 22, speed: 0 },
            { temp: 23, speed: 0 },
            { temp: 24, speed: 0 },
            { temp: 25, speed: 0 },
            { temp: 26, speed: 0 },
            { temp: 27, speed: 0 },
            { temp: 28, speed: 0 },
            { temp: 29, speed: 0 },
            { temp: 30, speed: 10 },
            { temp: 31, speed: 10 },
            { temp: 32, speed: 10 },
            { temp: 33, speed: 10 },
            { temp: 34, speed: 10 },
            { temp: 35, speed: 10 },
            { temp: 36, speed: 10 },
            { temp: 37, speed: 10 },
            { temp: 38, speed: 10 },
            { temp: 39, speed: 10 },
            { temp: 40, speed: 10 },
            { temp: 41, speed: 10 },
            { temp: 42, speed: 10 },
            { temp: 43, speed: 10 },
            { temp: 44, speed: 10 },
            { temp: 45, speed: 10 },
            { temp: 46, speed: 10 },
            { temp: 47, speed: 10 },
            { temp: 48, speed: 10 },
            { temp: 49, speed: 10 },
            { temp: 50, speed: 10 },
            { temp: 51, speed: 10 },
            { temp: 52, speed: 10 },
            { temp: 53, speed: 10 },
            { temp: 54, speed: 10 },
            { temp: 55, speed: 28 },
            { temp: 56, speed: 28 },
            { temp: 57, speed: 28 },
            { temp: 58, speed: 28 },
            { temp: 59, speed: 28 },
            { temp: 60, speed: 28 },
            { temp: 61, speed: 28 },
            { temp: 62, speed: 28 },
            { temp: 63, speed: 28 },
            { temp: 64, speed: 28 },
            { temp: 65, speed: 28 },
            { temp: 66, speed: 28 },
            { temp: 67, speed: 28 },
            { temp: 68, speed: 28 },
            { temp: 69, speed: 28 },
            { temp: 70, speed: 28 },
            { temp: 71, speed: 28 },
            { temp: 72, speed: 28 },
            { temp: 73, speed: 28 },
            { temp: 74, speed: 28 },
            { temp: 75, speed: 28 },
            { temp: 76, speed: 28 },
            { temp: 77, speed: 28 },
            { temp: 78, speed: 28 },
            { temp: 79, speed: 28 },
            { temp: 80, speed: 28 },
            { temp: 81, speed: 28 },
            { temp: 82, speed: 28 },
            { temp: 83, speed: 28 },
            { temp: 84, speed: 28 },
            { temp: 85, speed: 28 },
            { temp: 86, speed: 28 },
            { temp: 87, speed: 28 },
            { temp: 88, speed: 28 },
            { temp: 89, speed: 28 },
            { temp: 90, speed: 28 },
            { temp: 91, speed: 28 },
            { temp: 92, speed: 28 },
            { temp: 93, speed: 28 },
            { temp: 94, speed: 28 },
            { temp: 95, speed: 28 },
            { temp: 96, speed: 28 },
            { temp: 97, speed: 28 },
            { temp: 98, speed: 25 },
            { temp: 99, speed: 25 },
            { temp: 100, speed: 25 }
        ],
    },
    {
        name: "Quiet",
        tableCPU: [
            { temp: 0, speed: 0 },
            { temp: 1, speed: 0 },
            { temp: 2, speed: 0 },
            { temp: 3, speed: 0 },
            { temp: 4, speed: 0 },
            { temp: 5, speed: 0 },
            { temp: 6, speed: 0 },
            { temp: 7, speed: 0 },
            { temp: 8, speed: 0 },
            { temp: 9, speed: 0 },
            { temp: 10, speed: 0 },
            { temp: 11, speed: 0 },
            { temp: 12, speed: 0 },
            { temp: 13, speed: 0 },
            { temp: 14, speed: 0 },
            { temp: 15, speed: 0 },
            { temp: 16, speed: 0 },
            { temp: 17, speed: 0 },
            { temp: 18, speed: 0 },
            { temp: 19, speed: 0 },
            { temp: 20, speed: 0 },
            { temp: 21, speed: 0 },
            { temp: 22, speed: 24 },
            { temp: 23, speed: 24 },
            { temp: 24, speed: 24 },
            { temp: 25, speed: 24 },
            { temp: 26, speed: 24 },
            { temp: 27, speed: 24 },
            { temp: 28, speed: 24 },
            { temp: 29, speed: 24 },
            { temp: 30, speed: 24 },
            { temp: 31, speed: 24 },
            { temp: 32, speed: 24 },
            { temp: 33, speed: 24 },
            { temp: 34, speed: 24 },
            { temp: 35, speed: 24 },
            { temp: 36, speed: 24 },
            { temp: 37, speed: 24 },
            { temp: 38, speed: 24 },
            { temp: 39, speed: 24 },
            { temp: 40, speed: 24 },
            { temp: 41, speed: 24 },
            { temp: 42, speed: 24 },
            { temp: 43, speed: 24 },
            { temp: 44, speed: 24 },
            { temp: 45, speed: 24 },
            { temp: 46, speed: 24 },
            { temp: 47, speed: 24 },
            { temp: 48, speed: 24 },
            { temp: 49, speed: 24 },
            { temp: 50, speed: 25 },
            { temp: 51, speed: 25 },
            { temp: 52, speed: 35 },
            { temp: 53, speed: 35 },
            { temp: 54, speed: 35 },
            { temp: 55, speed: 35 },
            { temp: 56, speed: 35 },
            { temp: 57, speed: 40 },
            { temp: 58, speed: 50 },
            { temp: 59, speed: 60 },
            { temp: 60, speed: 70 },
            { temp: 61, speed: 70 },
            { temp: 62, speed: 70 },
            { temp: 63, speed: 70 },
            { temp: 64, speed: 70 },
            { temp: 65, speed: 70 },
            { temp: 66, speed: 70 },
            { temp: 67, speed: 70 },
            { temp: 68, speed: 70 },
            { temp: 69, speed: 70 },
            { temp: 70, speed: 70 },
            { temp: 71, speed: 70 },
            { temp: 72, speed: 70 },
            { temp: 73, speed: 70 },
            { temp: 74, speed: 70 },
            { temp: 75, speed: 70 },
            { temp: 76, speed: 70 },
            { temp: 77, speed: 70 },
            { temp: 78, speed: 70 },
            { temp: 79, speed: 70 },
            { temp: 80, speed: 74 },
            { temp: 81, speed: 74 },
            { temp: 82, speed: 74 },
            { temp: 83, speed: 74 },
            { temp: 84, speed: 74 },
            { temp: 85, speed: 74 },
            { temp: 86, speed: 74 },
            { temp: 87, speed: 74 },
            { temp: 88, speed: 74 },
            { temp: 89, speed: 74 },
            { temp: 90, speed: 74 },
            { temp: 91, speed: 74 },
            { temp: 92, speed: 74 },
            { temp: 93, speed: 74 },
            { temp: 94, speed: 74 },
            { temp: 95, speed: 74 },
            { temp: 96, speed: 77 },
            { temp: 97, speed: 77 },
            { temp: 98, speed: 80 },
            { temp: 99, speed: 80 },
            { temp: 100, speed: 80 }
        ],
        tableGPU: [
            { temp: 0, speed: 0 },
            { temp: 1, speed: 0 },
            { temp: 2, speed: 0 },
            { temp: 3, speed: 0 },
            { temp: 4, speed: 0 },
            { temp: 5, speed: 0 },
            { temp: 6, speed: 0 },
            { temp: 7, speed: 0 },
            { temp: 8, speed: 0 },
            { temp: 9, speed: 0 },
            { temp: 10, speed: 0 },
            { temp: 11, speed: 0 },
            { temp: 12, speed: 0 },
            { temp: 13, speed: 0 },
            { temp: 14, speed: 0 },
            { temp: 15, speed: 0 },
            { temp: 16, speed: 0 },
            { temp: 17, speed: 0 },
            { temp: 18, speed: 0 },
            { temp: 19, speed: 0 },
            { temp: 20, speed: 0 },
            { temp: 21, speed: 0 },
            { temp: 22, speed: 0 },
            { temp: 23, speed: 0 },
            { temp: 24, speed: 0 },
            { temp: 25, speed: 0 },
            { temp: 26, speed: 0 },
            { temp: 27, speed: 18 },
            { temp: 28, speed: 18 },
            { temp: 29, speed: 18 },
            { temp: 30, speed: 18 },
            { temp: 31, speed: 18 },
            { temp: 32, speed: 18 },
            { temp: 33, speed: 18 },
            { temp: 34, speed: 18 },
            { temp: 35, speed: 18 },
            { temp: 36, speed: 18 },
            { temp: 37, speed: 18 },
            { temp: 38, speed: 18 },
            { temp: 39, speed: 18 },
            { temp: 40, speed: 18 },
            { temp: 41, speed: 18 },
            { temp: 42, speed: 18 },
            { temp: 43, speed: 18 },
            { temp: 44, speed: 18 },
            { temp: 45, speed: 18 },
            { temp: 46, speed: 18 },
            { temp: 47, speed: 18 },
            { temp: 48, speed: 18 },
            { temp: 49, speed: 18 },
            { temp: 50, speed: 18 },
            { temp: 51, speed: 22 },
            { temp: 52, speed: 30 },
            { temp: 53, speed: 40 },
            { temp: 54, speed: 50 },
            { temp: 55, speed: 60 },
            { temp: 56, speed: 68 },
            { temp: 57, speed: 68 },
            { temp: 58, speed: 68 },
            { temp: 59, speed: 68 },
            { temp: 60, speed: 68 },
            { temp: 61, speed: 68 },
            { temp: 62, speed: 68 },
            { temp: 63, speed: 68 },
            { temp: 64, speed: 68 },
            { temp: 65, speed: 68 },
            { temp: 66, speed: 68 },
            { temp: 67, speed: 68 },
            { temp: 68, speed: 68 },
            { temp: 69, speed: 68 },
            { temp: 70, speed: 68 },
            { temp: 71, speed: 68 },
            { temp: 72, speed: 68 },
            { temp: 73, speed: 68 },
            { temp: 74, speed: 68 },
            { temp: 75, speed: 68 },
            { temp: 76, speed: 68 },
            { temp: 77, speed: 68 },
            { temp: 78, speed: 68 },
            { temp: 79, speed: 68 },
            { temp: 80, speed: 68 },
            { temp: 81, speed: 68 },
            { temp: 82, speed: 68 },
            { temp: 83, speed: 68 },
            { temp: 84, speed: 68 },
            { temp: 85, speed: 68 },
            { temp: 86, speed: 68 },
            { temp: 87, speed: 68 },
            { temp: 88, speed: 68 },
            { temp: 89, speed: 70 },
            { temp: 90, speed: 70 },
            { temp: 91, speed: 70 },
            { temp: 92, speed: 70 },
            { temp: 93, speed: 70 },
            { temp: 94, speed: 70 },
            { temp: 95, speed: 70 },
            { temp: 96, speed: 75 },
            { temp: 97, speed: 75 },
            { temp: 98, speed: 80 },
            { temp: 99, speed: 80 },
            { temp: 100, speed: 80 }
        ],
    },
    {
        name: "Balanced",
        tableCPU: [
            { temp: 0, speed: 0 },
            { temp: 1, speed: 0 },
            { temp: 2, speed: 0 },
            { temp: 3, speed: 0 },
            { temp: 4, speed: 0 },
            { temp: 5, speed: 0 },
            { temp: 6, speed: 0 },
            { temp: 7, speed: 0 },
            { temp: 8, speed: 0 },
            { temp: 9, speed: 0 },
            { temp: 10, speed: 0 },
            { temp: 11, speed: 0 },
            { temp: 12, speed: 0 },
            { temp: 13, speed: 0 },
            { temp: 14, speed: 0 },
            { temp: 15, speed: 0 },
            { temp: 16, speed: 0 },
            { temp: 17, speed: 0 },
            { temp: 18, speed: 0 },
            { temp: 19, speed: 0 },
            { temp: 20, speed: 0 },
            { temp: 21, speed: 0 },
            { temp: 22, speed: 0 },
            { temp: 23, speed: 0 },
            { temp: 24, speed: 0 },
            { temp: 25, speed: 0 },
            { temp: 26, speed: 0 },
            { temp: 27, speed: 0 },
            { temp: 28, speed: 0 },
            { temp: 29, speed: 0 },
            { temp: 30, speed: 0 },
            { temp: 31, speed: 0 },
            { temp: 32, speed: 0 },
            { temp: 33, speed: 0 },
            { temp: 34, speed: 0 },
            { temp: 35, speed: 0 },
            { temp: 36, speed: 0 },
            { temp: 37, speed: 0 },
            { temp: 38, speed: 0 },
            { temp: 39, speed: 0 },
            { temp: 40, speed: 0 },
            { temp: 41, speed: 0 },
            { temp: 42, speed: 0 },
            { temp: 43, speed: 0 },
            { temp: 44, speed: 0 },
            { temp: 45, speed: 0 },
            { temp: 46, speed: 0 },
            { temp: 47, speed: 0 },
            { temp: 48, speed: 0 },
            { temp: 49, speed: 0 },
            { temp: 50, speed: 3 },
            { temp: 51, speed: 3 },
            { temp: 52, speed: 3 },
            { temp: 53, speed: 3 },
            { temp: 54, speed: 3 },
            { temp: 55, speed: 3 },
            { temp: 56, speed: 3 },
            { temp: 57, speed: 3 },
            { temp: 58, speed: 3 },
            { temp: 59, speed: 3 },
            { temp: 60, speed: 3 },
            { temp: 61, speed: 3 },
            { temp: 62, speed: 3 },
            { temp: 63, speed: 3 },
            { temp: 64, speed: 3 },
            { temp: 65, speed: 3 },
            { temp: 66, speed: 3 },
            { temp: 67, speed: 3 },
            { temp: 68, speed: 3 },
            { temp: 69, speed: 3 },
            { temp: 70, speed: 3 },
            { temp: 71, speed: 3 },
            { temp: 72, speed: 3 },
            { temp: 73, speed: 3 },
            { temp: 74, speed: 3 },
            { temp: 75, speed: 3 },
            { temp: 76, speed: 3 },
            { temp: 77, speed: 3 },
            { temp: 78, speed: 3 },
            { temp: 79, speed: 3 },
            { temp: 80, speed: 3 },
            { temp: 81, speed: 3 },
            { temp: 82, speed: 3 },
            { temp: 83, speed: 3 },
            { temp: 84, speed: 3 },
            { temp: 85, speed: 3 },
            { temp: 86, speed: 3 },
            { temp: 87, speed: 3 },
            { temp: 88, speed: 3 },
            { temp: 89, speed: 3 },
            { temp: 90, speed: 3 },
            { temp: 91, speed: 3 },
            { temp: 92, speed: 3 },
            { temp: 93, speed: 3 },
            { temp: 94, speed: 3 },
            { temp: 95, speed: 3 },
            { temp: 96, speed: 3 },
            { temp: 97, speed: 3 },
            { temp: 98, speed: 3 },
            { temp: 99, speed: 3 },
            { temp: 100, speed: 3 }
        ],
                tableGPU: [
            { temp: 0, speed: 0 },
            { temp: 1, speed: 0 },
            { temp: 2, speed: 0 },
            { temp: 3, speed: 0 },
            { temp: 4, speed: 0 },
            { temp: 5, speed: 0 },
            { temp: 6, speed: 0 },
            { temp: 7, speed: 0 },
            { temp: 8, speed: 0 },
            { temp: 9, speed: 0 },
            { temp: 10, speed: 0 },
            { temp: 11, speed: 0 },
            { temp: 12, speed: 0 },
            { temp: 13, speed: 0 },
            { temp: 14, speed: 0 },
            { temp: 15, speed: 0 },
            { temp: 16, speed: 0 },
            { temp: 17, speed: 0 },
            { temp: 18, speed: 0 },
            { temp: 19, speed: 0 },
            { temp: 20, speed: 0 },
            { temp: 21, speed: 0 },
            { temp: 22, speed: 0 },
            { temp: 23, speed: 0 },
            { temp: 24, speed: 0 },
            { temp: 25, speed: 0 },
            { temp: 26, speed: 0 },
            { temp: 27, speed: 0 },
            { temp: 28, speed: 0 },
            { temp: 29, speed: 0 },
            { temp: 30, speed: 0 },
            { temp: 31, speed: 0 },
            { temp: 32, speed: 0 },
            { temp: 33, speed: 0 },
            { temp: 34, speed: 0 },
            { temp: 35, speed: 0 },
            { temp: 36, speed: 0 },
            { temp: 37, speed: 0 },
            { temp: 38, speed: 0 },
            { temp: 39, speed: 0 },
            { temp: 40, speed: 0 },
            { temp: 41, speed: 0 },
            { temp: 42, speed: 0 },
            { temp: 43, speed: 0 },
            { temp: 44, speed: 0 },
            { temp: 45, speed: 0 },
            { temp: 46, speed: 0 },
            { temp: 47, speed: 0 },
            { temp: 48, speed: 0 },
            { temp: 49, speed: 0 },
            { temp: 50, speed: 0 },
            { temp: 51, speed: 0 },
            { temp: 52, speed: 0 },
            { temp: 53, speed: 0 },
            { temp: 54, speed: 0 },
            { temp: 55, speed: 0 },
            { temp: 56, speed: 0 },
            { temp: 57, speed: 0 },
            { temp: 58, speed: 0 },
            { temp: 59, speed: 0 },
            { temp: 60, speed: 0 },
            { temp: 61, speed: 0 },
            { temp: 62, speed: 0 },
            { temp: 63, speed: 0 },
            { temp: 64, speed: 0 },
            { temp: 65, speed: 0 },
            { temp: 66, speed: 0 },
            { temp: 67, speed: 0 },
            { temp: 68, speed: 0 },
            { temp: 69, speed: 0 },
            { temp: 70, speed: 0 },
            { temp: 71, speed: 0 },
            { temp: 72, speed: 0 },
            { temp: 73, speed: 0 },
            { temp: 74, speed: 0 },
            { temp: 75, speed: 0 },
            { temp: 76, speed: 0 },
            { temp: 77, speed: 0 },
            { temp: 78, speed: 0 },
            { temp: 79, speed: 0 },
            { temp: 80, speed: 0 },
            { temp: 81, speed: 0 },
            { temp: 82, speed: 0 },
            { temp: 83, speed: 0 },
            { temp: 84, speed: 0 },
            { temp: 85, speed: 0 },
            { temp: 86, speed: 0 },
            { temp: 87, speed: 0 },
            { temp: 88, speed: 0 },
            { temp: 89, speed: 0 },
            { temp: 90, speed: 0 },
            { temp: 91, speed: 100 },
            { temp: 92, speed: 100 },
            { temp: 93, speed: 100 },
            { temp: 94, speed: 100 },
            { temp: 95, speed: 100 },
            { temp: 96, speed: 100 },
            { temp: 97, speed: 100 },
            { temp: 98, speed: 100 },
            { temp: 99, speed: 100 },
            { temp: 100, speed: 100 },
        ],
    },
    {
        name: "Cool",
        tableCPU: [
            { temp: 0, speed: 0 },
            { temp: 1, speed: 0 },
            { temp: 2, speed: 0 },
            { temp: 3, speed: 0 },
            { temp: 4, speed: 0 },
            { temp: 5, speed: 0 },
            { temp: 6, speed: 0 },
            { temp: 7, speed: 0 },
            { temp: 8, speed: 0 },
            { temp: 9, speed: 0 },
            { temp: 10, speed: 0 },
            { temp: 11, speed: 0 },
            { temp: 12, speed: 0 },
            { temp: 13, speed: 0 },
            { temp: 14, speed: 0 },
            { temp: 15, speed: 0 },
            { temp: 16, speed: 0 },
            { temp: 17, speed: 0 },
            { temp: 18, speed: 0 },
            { temp: 19, speed: 0 },
            { temp: 20, speed: 0 },
            { temp: 21, speed: 0 },
            { temp: 22, speed: 0 },
            { temp: 23, speed: 0 },
            { temp: 24, speed: 0 },
            { temp: 25, speed: 0 },
            { temp: 26, speed: 0 },
            { temp: 27, speed: 0 },
            { temp: 28, speed: 0 },
            { temp: 29, speed: 0 },
            { temp: 30, speed: 0 },
            { temp: 31, speed: 0 },
            { temp: 32, speed: 0 },
            { temp: 33, speed: 0 },
            { temp: 34, speed: 0 },
            { temp: 35, speed: 0 },
            { temp: 36, speed: 0 },
            { temp: 37, speed: 0 },
            { temp: 38, speed: 0 },
            { temp: 39, speed: 0 },
            { temp: 40, speed: 20 },
            { temp: 41, speed: 20 },
            { temp: 42, speed: 20 },
            { temp: 43, speed: 20 },
            { temp: 44, speed: 20 },
            { temp: 45, speed: 20 },
            { temp: 46, speed: 25 },
            { temp: 47, speed: 25 },
            { temp: 48, speed: 25 },
            { temp: 49, speed: 25 },
            { temp: 50, speed: 25 },
            { temp: 51, speed: 30 },
            { temp: 52, speed: 30 },
            { temp: 53, speed: 30 },
            { temp: 54, speed: 30 },
            { temp: 55, speed: 30 },
            { temp: 56, speed: 32 },
            { temp: 57, speed: 33 },
            { temp: 58, speed: 34 },
            { temp: 59, speed: 35 },
            { temp: 60, speed: 35 },
            { temp: 61, speed: 37 },
            { temp: 62, speed: 40 },
            { temp: 63, speed: 40 },
            { temp: 64, speed: 42 },
            { temp: 65, speed: 45 },
            { temp: 66, speed: 45 },
            { temp: 67, speed: 45 },
            { temp: 68, speed: 47 },
            { temp: 69, speed: 50 },
            { temp: 70, speed: 50 },
            { temp: 71, speed: 52 },
            { temp: 72, speed: 55 },
            { temp: 73, speed: 55 },
            { temp: 74, speed: 57 },
            { temp: 75, speed: 60 },
            { temp: 76, speed: 60 },
            { temp: 77, speed: 65 },
            { temp: 78, speed: 65 },
            { temp: 79, speed: 70 },
            { temp: 80, speed: 70 },
            { temp: 81, speed: 75 },
            { temp: 82, speed: 75 },
            { temp: 83, speed: 80 },
            { temp: 84, speed: 80 },
            { temp: 85, speed: 85 },
            { temp: 86, speed: 85 },
            { temp: 87, speed: 90 },
            { temp: 88, speed: 90 },
            { temp: 89, speed: 90 },
            { temp: 90, speed: 95 },
            { temp: 91, speed: 95 },
            { temp: 92, speed: 95 },
            { temp: 93, speed: 95 },
            { temp: 94, speed: 95 },
            { temp: 95, speed: 100 },
            { temp: 96, speed: 100 },
            { temp: 97, speed: 100 },
            { temp: 98, speed: 100 },
            { temp: 99, speed: 100 },
            { temp: 100, speed: 100 },
        ],
        tableGPU: [
            { temp: 0, speed: 0 },
            { temp: 1, speed: 0 },
            { temp: 2, speed: 0 },
            { temp: 3, speed: 0 },
            { temp: 4, speed: 0 },
            { temp: 5, speed: 0 },
            { temp: 6, speed: 0 },
            { temp: 7, speed: 0 },
            { temp: 8, speed: 0 },
            { temp: 9, speed: 0 },
            { temp: 10, speed: 0 },
            { temp: 11, speed: 0 },
            { temp: 12, speed: 0 },
            { temp: 13, speed: 0 },
            { temp: 14, speed: 0 },
            { temp: 15, speed: 0 },
            { temp: 16, speed: 0 },
            { temp: 17, speed: 0 },
            { temp: 18, speed: 0 },
            { temp: 19, speed: 0 },
            { temp: 20, speed: 0 },
            { temp: 21, speed: 0 },
            { temp: 22, speed: 0 },
            { temp: 23, speed: 0 },
            { temp: 24, speed: 0 },
            { temp: 25, speed: 0 },
            { temp: 26, speed: 0 },
            { temp: 27, speed: 0 },
            { temp: 28, speed: 0 },
            { temp: 29, speed: 0 },
            { temp: 30, speed: 0 },
            { temp: 31, speed: 0 },
            { temp: 32, speed: 0 },
            { temp: 33, speed: 0 },
            { temp: 34, speed: 0 },
            { temp: 35, speed: 0 },
            { temp: 36, speed: 0 },
            { temp: 37, speed: 0 },
            { temp: 38, speed: 0 },
            { temp: 39, speed: 0 },
            { temp: 40, speed: 25 },
            { temp: 41, speed: 25 },
            { temp: 42, speed: 25 },
            { temp: 43, speed: 25 },
            { temp: 44, speed: 25 },
            { temp: 45, speed: 30 },
            { temp: 46, speed: 30 },
            { temp: 47, speed: 30 },
            { temp: 48, speed: 30 },
            { temp: 49, speed: 30 },
            { temp: 50, speed: 35 },
            { temp: 51, speed: 35 },
            { temp: 52, speed: 35 },
            { temp: 53, speed: 35 },
            { temp: 54, speed: 35 },
            { temp: 55, speed: 40 },
            { temp: 56, speed: 40 },
            { temp: 57, speed: 40 },
            { temp: 58, speed: 40 },
            { temp: 59, speed: 40 },
            { temp: 60, speed: 45 },
            { temp: 61, speed: 45 },
            { temp: 62, speed: 45 },
            { temp: 63, speed: 45 },
            { temp: 64, speed: 45 },
            { temp: 65, speed: 50 },
            { temp: 66, speed: 50 },
            { temp: 67, speed: 50 },
            { temp: 68, speed: 50 },
            { temp: 69, speed: 50 },
            { temp: 70, speed: 60 },
            { temp: 71, speed: 60 },
            { temp: 72, speed: 60 },
            { temp: 73, speed: 60 },
            { temp: 74, speed: 60 },
            { temp: 75, speed: 70 },
            { temp: 76, speed: 70 },
            { temp: 77, speed: 70 },
            { temp: 78, speed: 70 },
            { temp: 79, speed: 70 },
            { temp: 80, speed: 75 },
            { temp: 81, speed: 75 },
            { temp: 82, speed: 75 },
            { temp: 83, speed: 75 },
            { temp: 84, speed: 75 },
            { temp: 85, speed: 85 },
            { temp: 86, speed: 85 },
            { temp: 87, speed: 90 },
            { temp: 88, speed: 90 },
            { temp: 89, speed: 95 },
            { temp: 90, speed: 95 },
            { temp: 91, speed: 100 },
            { temp: 92, speed: 100 },
            { temp: 93, speed: 100 },
            { temp: 94, speed: 100 },
            { temp: 95, speed: 100 },
            { temp: 96, speed: 100 },
            { temp: 97, speed: 100 },
            { temp: 98, speed: 100 },
            { temp: 99, speed: 100 },
            { temp: 100, speed: 100 },
        ],
    },
    {
        name: "Custom",
    },
];

export const customFanPreset: ITccFanProfile = {
    tableCPU: [
        { temp: 20, speed: 12 },
        { temp: 30, speed: 14 },
        { temp: 40, speed: 22 },
        { temp: 50, speed: 35 },
        { temp: 60, speed: 44 },
        { temp: 70, speed: 56 },
        { temp: 80, speed: 79 },
        { temp: 90, speed: 85 },
        { temp: 100, speed: 90 },
    ],
    tableGPU: [
        { temp: 20, speed: 12 },
        { temp: 30, speed: 14 },
        { temp: 40, speed: 22 },
        { temp: 50, speed: 35 },
        { temp: 60, speed: 44 },
        { temp: 70, speed: 56 },
        { temp: 80, speed: 79 },
        { temp: 90, speed: 85 },
        { temp: 100, speed: 90 },
    ]
};




// Add at the end of file
export const MIN_FAN_POINTS = 1;
export const MAX_FAN_POINTS = 20;
export const MIN_TEMP = 0;
export const MAX_TEMP = 100;
export const MIN_SPEED = 0;
export const MAX_SPEED = 100;

export function validateFanProfile(profile: ITccFanProfile): boolean {
    if (!profile) return false;
    
    if (profile.tableCPU) {
        if (profile.tableCPU.length < MIN_FAN_POINTS || 
            profile.tableCPU.length > MAX_FAN_POINTS) {
            return false;
        }
        
        for (let i = 1; i < profile.tableCPU.length; i++) {
            if (profile.tableCPU[i].temp <= profile.tableCPU[i-1].temp) {
                return false;
            }
        }
    }
    
    if (profile.tableGPU) {
        if (profile.tableGPU.length < MIN_FAN_POINTS || 
            profile.tableGPU.length > MAX_FAN_POINTS) {
            return false;
        }
        
        for (let i = 1; i < profile.tableGPU.length; i++) {
            if (profile.tableGPU[i].temp <= profile.tableGPU[i-1].temp) {
                return false;
            }
        }
    }
    
    return true;
}
